# Netlify configuration

[build]
  functions = "WEB/netlify/functions"

# Block direct HTTP access to the /backend/ folder
[[redirects]]
  from = "/backend/*"
  to = "/404"
  status = 404
  force = true
